-- table creation

CREATE TABLE CITIES(
CITY_ID INTEGER PRIMARY KEY,
CITY CHAR(20),
STATE CHAR(20)
);

CREATE TABLE WAREHOUSES(
WID INT PRIMARY KEY,
WNAME CHAR(30),
LOCATION CHAR(20),
EXTRA json,
CITY_ID INT,
FOREIGN KEY(CITY_ID) references CITIES(CITY_ID)
);

CREATE TABLE STORES(
SID INTEGER PRIMARY KEY,
STORE_NAME CHAR(20), 
LOCATION_CITY CHAR(20),
WAREHOUSE_ID INTEGER,
FOREIGN KEY(WAREHOUSE_ID) references WAREHOUSES(WID)
);

CREATE TABLE CUSTOMER(
CNO INTEGER PRIMARY KEY, 
CNAME CHAR(50),
ADDR VARCHAR(50),
CU_CITY CHAR(20));

CREATE TABLE ORDERS(
ONO INT PRIMARY KEY,
ODATE DATE,
CUSTOMER_ID INT,
FOREIGN KEY(CUSTOMER_ID) references CUSTOMER(CNO)
);

CREATE TABLE ITEMS(
ITEMNO INT PRIMARY KEY,
DESCRIPTION TEXT,
WEIGHT DECIMAL(5,2),
COST DECIMAL(5,2)
);

-- Many to Many relationship

CREATE TABLE STORES_ITEMS_RELATION(
STORE_ID INTEGER NOT NULL,
ITEM_ID INTEGER NOT NULL,
quantity INT,
FOREIGN KEY(STORE_ID) references STORES(STORE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(ITEM_ID) references ITEMS(ITEMNO) ON DELETE RESTRICT ON UPDATE CASCADE,
UNIQUE(STORE_ID,ITEM_ID)
)

CREATE TABLE ORDERS_ITEMS_RELATION(
ORDER_ID INTEGER NOT NULL,
ITEM_ID INTEGER NOT NULL,
ordered_quantity INT,
FOREIGN KEY(ORDER_ID) references ORDERS(ONO) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(ITEM_ID) references ITEMS(ITEMNO) ON DELETE RESTRICT ON UPDATE CASCADE,
UNIQUE(ORDER_ID,ITEM_ID)
)

-- Inserting data...

INSERT INTO CITIES(CITY, STATE) VALUES ('Mumbai', 'Maharastra');
INSERT INTO CITIES(CITY, STATE) VALUES ('Pune', 'Maharastra');


INSERT INTO WAREHOUSES(
WNAME,
LOCATION,
EXTRA,
CITY_ID)  VALUES (
'W1',
'Main road, Pune',
'{"branches": "2"}',
'1'
);

INSERT INTO WAREHOUSES(
WNAME,
LOCATION,
EXTRA,
CITY_ID)  VALUES (
'W2',
'KP NAGAR, Mumbai',
'{"branches": "3"}',
'2'
);

INSERT INTO STORES(
STORE_NAME, 
LOCATION_CITY,
WAREHOUSE_ID)  VALUES (
'Store 1',
'XYZ road, Mumbai',
'2'
);

INSERT INTO STORES(
STORE_NAME, 
LOCATION_CITY,
WAREHOUSE_ID)  VALUES (
'Store 2',
'ABC road, Pune',
'1'
);

INSERT INTO STORES(
STORE_NAME, 
LOCATION_CITY,
WAREHOUSE_ID)  VALUES (
'Store 3',
'Laxmi Nagar, Pune',
'1'
);

INSERT INTO CUSTOMER(
CNAME,
ADDR,
CU_CITY)  VALUES (
'Adam',
'1332 street, Near Lakshman Chowk',
'Pune'
);

INSERT INTO CUSTOMER(
CNAME,
ADDR,
CU_CITY)  VALUES (
'Smith',
'342B road, near gayatri colony',
'Mumbai'
);

INSERT INTO ORDERS(
ODATE,
CUSTOMER_ID)  VALUES (
'05-02-2022',
'1'
);

INSERT INTO ORDERS(
ODATE,
CUSTOMER_ID)  VALUES (
'08-05-2022',
'1'
);

INSERT INTO ORDERS(
ODATE,
CUSTOMER_ID)  VALUES (
'02-09-2022',
'2'
);

INSERT INTO ORDERS(
ODATE,
CUSTOMER_ID)  VALUES (
'01-08-2022',
'1'
);

INSERT INTO ITEMS(
DESCRIPTION,
WEIGHT,
COST)  VALUES (
'Samsung S12 Mobile',
'250g',
'34000 INR'
);

INSERT INTO ITEMS(
DESCRIPTION,
WEIGHT,
COST)  VALUES (
'Boat Eardopes',
'100g',
'400 INR'
);

INSERT INTO ITEMS(
DESCRIPTION,
WEIGHT,
COST)  VALUES (
'Apple Smart Watch',
'120g',
'45000 INR'
);


-- Inserting into M:M table

INSERT INTO ORDERS_ITEMS_RELATION (ORDER_ID, ITEM_ID)
SELECT ORDERS.ONO, ITEMS.ITEMNO FROM ORDERS CROSS JOIN ITEMS;
